### ISSUE TITLE
Gap Generator

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#19]
Sleeper factory allows you to build a 'Gap Generator', a 3x3 dense building, that covers a 15x15 size area on the map in total darkness. Needs to be populated, and can be bombed as normal.

**Comment by Deceth** [comment]
I believe such an item as described would be the source of much confusion?!

**Comment by Rushing** [comment]
Indeed, that's the whole Idea. I often will attempt to rush with the map open, with the gap generator,it would completely mess me up!

**Comment by Deceth** [comment]
Ah, you're talking about the "map". I thought you meant while in normal view, which would look like you're bugged or the sector didn't load. 

Cloaking your city on the 'map' could be useful. You could run right into a city and die from turrets even though it looked like nothing was ahead yet on the map...

**Comment by Rushing** [comment]
Presicely! It's a dastardly evil concept with devilish implications

**Comment by Deceth** [comment]
So, while I enjoy dastardly evil concepts with devilish implications, I don't think the time is right for this sort of item. Battle City is confusing enough as is for a new player, but once you learn the basics, (i.e., how to shoot, how to pick-up items, how to use items) you're pretty much ready to go. 

And so, there is this sort of simplistic beauty that makes the game addictive, because, once you get over the initial hump, you know exactly what to do. It's not easy to actually go ahead and succeed against good players, which is what makes the game so addictive, but at least you know what you're doing. 

Items like this could disrupt that simplistic beauty and confuse players unnecessarily. We want to add layers of strategy, while sticking to the basics. 

To do that, new items should stick to the existing recipe:
- build a factory
- it makes items
- you pick the items up, 
- you use or drop the items

If new items fit that mold, they aren't confusing at all, because they work like everything else. Sure, you might have to figure out what the item actually does or the best way to use is strategically, but you already know how it works immediately.
