### ISSUE TITLE
Convert database from SQLite to MySQL

### ISSUE THREAD

**Issue by Deceth** [Deceth/Battle-City#42]
This would allow for the game database and website database to be merged which would open up some interesting possibilities on the website such as the ability to browse players, scores, stats, etc.. 

Also, certain things that would be more difficult to implement in-game could then be done via the website such as profile management & clan management. 

Also, same password on game + site would be nice.

**Comment by Rushing** [comment]
When I first took a peek at the source I wondered why you never did this anyway. MySQL is easier to manage, and easier to operate from a company wide perspecitve.
The only downside is that MySQL is far easier to break into, but with the current population, I don't think that's much of an issue.

Now that I've said that, I suppose TECHNICALLY it's harder to break into, but because it's far more widely used, it's more well known how to break into.

**Comment by Deceth** [comment]
You bring up a good point. SQLite is much simpler than MySQL (With SQLite, there is no setup involved, you start the BC Server and the database creates itself). Switching to MySQL would make it very difficult for people to run their own server unless they know how to setup a MySQL database. The better option is to give the server host the option to use SQLite or MySQL.

**Comment by Rushing** [comment]
Hm, I guess that's an even idea, however it means quite a lot of programming to change.

**Comment by Deceth** [comment]
The only way to avoid the programming work is by not using MySQL. =p 

If we do decide to work on a version of BC compatible with MySQL, keeping the SQLite functionality isn't a big deal, it just means adding an if/else statement around what's already there so that the right code is used depending on the hosts database options.

**Comment by Rushing** [comment]
That's exactly what I meant. Not to be offensive, but you're not the sort of person that likes to do a lot of programming work, even if it's something as simple as adding in over nine thousand simple if/else statements.

**Comment by Deceth** [comment]
Either we speak a different dialect of English, or you've been sent by one of my enemies to cause my brain to implode.

**Comment by Rushing** [comment]
Probably a bit of both

**Comment by rileyw** [comment]
Converting the game database from SQLite to MySQL doesn't seem to be justified.

The game server can be set up to broadcast statistics from its game database. This would enable a website to capture this broadcast and use the data as it pleases.

The game server can be set up to point to a website database that manages player and clan data. The game server can poll this reference at set intervals to retrieve the data changes since the last poll.

Authentication between game and website may not be relevant if a central authentication system/server is created (Need an issue created for this idea). Game servers, websites, etc... would use hashes/tokens that identify the authenticated player similar to Google Single Sign-On or Facebook Login.

**Comment by Deceth** [comment]
I agree, SQLite is being maintained actively, there is no reason to put effort into migrating away.
