### ISSUE TITLE
Please create a battlecity with no errors

### ISSUE THREAD

**Issue by CanBoy67** [Deceth/Battle-City#45]
Deceth can you please make a BattleCity source code that does not have so many errors for people who are new to programming just one that you can download and build without errors i don't care if it has warnings they don't matter

**Comment by Deceth** [comment]
If it ain't broke, don't fix it! Oh wait... it's broke! 

If you're getting lots of errors, be sure to take a look at the Wiki article for setting up your development environment. You might be missing things that are necessary!

Technically, you should only be getting a few errors with the current source code ;)

**Comment by Rushing** [comment]
Actually Deceth, without FMod set up, I can receive ~50 errors upon compiling. Yay for FMod customer service being helpful enough to let us have the old version :)

**Comment by Deceth** [comment]
Until the repository is cleaned up, you can click "download" on this page to get the working source code for v3.5.7:

https://github.com/Deceth/Battle-City/commit/f73d8af78834be4ef1e5d36f366ef4bc5c248ebd

v3.5.8 still does not compile. Rather than fix it, I will eventually move this to it's own branch so it stops depriving pour souls from the opportunity of a lifetime - working on Battle City!

**Comment by Deceth** [comment]
The source code now compiles! Yay!

All unfinished code or items in development will hence-forth be done in branches outside of the master repository to avoid this sort of issue. The master repository will always contain a stable working version of the source code.
