### ISSUE TITLE
admin password

### ISSUE THREAD

**Issue by CanBoy67** [Deceth/Battle-City#46]
okay so i got the code running and i can play the game.  But what i don't know is the password
for the admin account is there one or do i have to make it myself.  If so how on earth
do i do it?
One more thing this is off-topic but how do i get the admin panel running?

**Comment by Deceth** [comment]
A button to open the admin panel will show up in-game when you are logged in as an administrator. It will be in the bottom right-hand corner.

To create your "first" administrator account, you will need to first create a normal account. Then you will need to open up the database and find the "IsAdmin" column for that user and change the value fro "0" to "1". 

In order to edit the database, you will need to get "SQLite".

**Comment by CanBoy67** [comment]
I'm sure this has nothing to do with this but how do you open the .db file with sqlite

**Comment by CanBoy67** [comment]
Nevermind if figured it out thanks for all the help Deceth
