### ISSUE TITLE
Declare our current version number

### ISSUE THREAD

**Issue by rileyw** [Deceth/Battle-City#54]
@Deceth What is our current version number?

**Comment by Deceth** [comment]
@rileyw The current code is version 3.5.7, declared in the file: CConstants.h on the client. The server checks the version and if it's not a match for what it can handle, the user will get an error message asking them to download the latest build.

I did release a build a few months ago that I called version 3.5.8, but I didn't update the source code because the only change I made was to the IP address to match the server I was hosting!

The idea being: 
Major Release . Minor Release . Bug Fix Release

The next planned release was to be 4.0.0 since everything more or less designed from previous development iterations has already been done and so we were at a point where we needed to define a next major release containing some of the things we've been talking about like player hosted servers, bots, better city loading, minimizing, and things we're still talking about or trying to nail down more specifically.

**Comment by rileyw** [comment]
@Deceth Could you apply the follow tags to the repository? The purpose is to identify official release commits that we can use to jump back into time to review code. New features will be handled as new branches of the master branch then merged into the master branch upon completion.

`git tag -a v3.4.6 -m "Version 3.4.6" 9237df232a`
`git tag -a v3.4.7 -m "Version 3.4.7" 6358276`
`git tag -a v3.4.8 -m "Version 3.4.8" e6b71d3`
`git tag -a v3.4.9 -m "Version 3.4.9" be2bad1`
`git tag -a v3.5.0 -m "Version 3.5.0" ba5820b`
`git tag -a v3.5.2 -m "Version 3.5.2" 243aff4`
`git tag -a v3.5.6 -m "Version 3.5.6" f31f789`
`git tag -a v3.5.7 -m "Version 3.5.7" 90339bd375`

Pull requests do not transfer the tags that I have set up in my forked repository.

**Comment by Deceth** [comment]
I don't have console access right now, but I'll do my darnedest to remember tagging tonight!

Good idea again @rileyw. I don't want things to be awkward or anything... but I thought you should know, you're awesome.

**Comment by Deceth** [comment]
Tags applied! Thanks for preparing the commands. You're teaching me a lot about the proper ways of using Git ;)
