### ISSUE TITLE
Server experiences CPPSQLITE_ERROR message

### ISSUE THREAD

**Issue by rileyw** [Deceth/Battle-City#59]
As a player logs into the server the server console will report a "CPPSQLITE_ERROR[1000] - Invalid field name requested" message. This is due to CAccount.cpp attempting to retrieve data for fields that do not exist in tAccounts.

``` c
            player->playerType = p->Database->Query.getIntField("IsAdmin");
            player->Town = p->Database->Query.getStringField("Town");
            player->Tank = p->Database->Query.getIntField("Tank");
            player->Tank2 = p->Database->Query.getIntField("Tank2");
            player->Tank3 = p->Database->Query.getIntField("Tank3");
            player->Tank4 = p->Database->Query.getIntField("Tank4");
            player->Tank5 = p->Database->Query.getIntField("Tank5");
            player->Tank6 = p->Database->Query.getIntField("Tank6");
            player->Tank7 = p->Database->Query.getIntField("Tank7");
            player->Tank8 = p->Database->Query.getIntField("Tank8");
            player->Tank9 = p->Database->Query.getIntField("Tank9");
            player->Red = p->Database->Query.getIntField("Red");
            player->Green = p->Database->Query.getIntField("Green");
            player->Blue = p->Database->Query.getIntField("Blue");
            player->Member = p->Database->Query.getIntField("Member");
            player->RentalCity = p->Database->Query.getIntField("RentalCity");
            p->Database->Query.finalize();
```

tAccounts has the following schema:

``` sql
CREATE TABLE tAccounts(AccountID INT PRIMARY KEY, Account CHAR(15), Password CHAR(15), Email CHAR(50), Fullname CHAR(20), Town char(15), State CHAR(15), Points INT DEFAULT 0, MonthlyTop20 INT DEFAULT 0, Orbs INT DEFAULT 0, Assists INT DEFAULT 0, Deaths INT DEFAULT 0, Member INT DEFAULT 0, IsAdmin INT DEFAULT 0);
```

The solution would be to either modify the tAccounts schema to include the missing fields or comment out the calls to invalid fields.

**Comment by Deceth** [comment]
If you open the actual database file (I think it's bcdata.db), with something like SQLiteManager, do you see all the fields or are they missing there? 

My bcdata.db does contain all the fields for Tank, Red, Green, Blue, Member and RentalCity. It looks like maybe, when the database was updated to include these fields, the source code for CREATE TABLE was not updated. And since we only had one server... nobody noticed until now, when you are testing on localhost with a freshly created server.

That being said, the fields are required, but some of these are the ones that need to be moved into their own table. For example, a player can have up to 9 different tanks right now. In-game, they can change between them if they have any, by pressing #'s 1,2,3...9. 

Ideally, this should be unlimited by having a separate table that links player id to tank id. 

The same goes for rental city. Now a player can have only one rental city. There should be a new table for this that links player id to city id, so a player can rent an unlimited amount of cities.

The Red, Green, Blue is used to allow a player to have a different name color in game. This should also be unlimited, and a player should have a button letting them scroll through all their name colors. (This wasn't as popular as Tanks and rental cities, but either way, it shouldn't be like this in the database.

The town field is really quite confusing. It's there for historical purposes because the original CodeHammer version had that... But really, it's only used as a field for players to show what clan they are in.. so really the database could benefit by adding two separate clan tables. One table that links player ID's to a clan ID. And one table that has columns for clanID, clanName, clanManager, (and then maybe some clan stats columns, like dayCreated, clanStatus,) 

Anyways, lots of what I'm saying are each separate issues to be created. **To answer your question, tAccounts schema needs to include the missing fields to fix this issue**. But... we should also change-up this schema in some other ways afterwards as we move into the future!

**Comment by rileyw** [comment]
Thank you for the clarification. I think you are correct that the CREATE TABLE statement was not updated to include the new fields. I'll update the CREATE TABLE command to include the updated schema.

**Comment by rileyw** [comment]
I agree that some database restructuring could be done. We can include these task types as features are implemented.
